### ISSUE TITLE
Add PUT endpoint for both skills and taxonomies

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/skills-api#12]
Add PUT endpoint for both skills and taxonomies

**Comment by SathyaJayabal** [comment]
We get the following error when we do not new values for name or taxonomyId fields. This will not allow you to update the record unless you change one of the two fields. Note same issue exists on PATCH. 
`{
    "message": "Skill already exists with taxonomyId:9cc0795a-6e12-4c84-9744-15858dba1861, name:jump6"
}`

<img width="1037" alt="Screenshot 2021-08-18 at 5 33 51 PM" src="https://user-images.githubusercontent.com/58783823/129895197-48d63e79-1cce-4f4b-832d-67a2672f59c1.png">

**Comment by SathyaJayabal** [comment]
Note: This is issue is not found in the taxonomies endpoint (PUT and PATCH)

**Comment by sandhiyakavi** [comment]
Verified in Dev Env.

PUT endpoint for skills is now allowing us to update even though the name and taxonomy id are not changed.
![image](https://user-images.githubusercontent.com/55895538/130022072-5974efc2-d6e6-4b2f-9845-4876da233418.png)

PUT endpoint for taxonomy is working fine as expected.
![image](https://user-images.githubusercontent.com/55895538/130023741-79afcb8b-3b78-473d-aee8-41dedebd0336.png)

**Comment by sandhiyakavi** [comment]
The same is working for PATCH endpoints of Skills and taxonomies as well.

![image](https://user-images.githubusercontent.com/55895538/130027431-c6ea201e-5646-40c5-83ba-d0b746535d91.png)
![image](https://user-images.githubusercontent.com/55895538/130027894-9c709df6-c557-4c00-bb00-f4189a6720bf.png)

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1680" alt="Screenshot 2021-08-19 at 6 32 20 PM" src="https://user-images.githubusercontent.com/58783823/130074124-fa8deb22-d3f1-49a3-a367-26d499e32436.png">
<img width="1680" alt="Screenshot 2021-08-19 at 6 32 02 PM" src="https://user-images.githubusercontent.com/58783823/130074140-967a0b11-79e0-4663-b930-dfe854ce85a7.png">
