### ISSUE TITLE
Add last-modified header to the HEAD endpoints for both skills and taxonomies

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/skills-api#13]
Add last-modified header to the HEAD endpoints for both skills and taxonomies

**Comment by SathyaJayabal** [comment]
@vikasrohit , I dont see the last-modified value in the headers
<img width="1440" alt="Screenshot 2021-08-18 at 5 48 38 PM" src="https://user-images.githubusercontent.com/58783823/129896884-c5f019ae-51c2-49a0-983b-717c100d60b7.png">

**Comment by sandhiyakavi** [comment]
Verified in Dev Env.

Last modified field is added to the response headers of HEAD endpoints for both Skills and taxonomies.
![image](https://user-images.githubusercontent.com/55895538/130024951-ad5bb030-5110-424e-a645-7ad0cb66e5f3.png)

![image](https://user-images.githubusercontent.com/55895538/130024493-900cd770-afae-4f62-bbdf-40b395b2521d.png)

**Comment by vikasrohit** [comment]
@sandhiyakavi are we getting response body in HEAD?

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-08-19 at 4 55 25 PM" src="https://user-images.githubusercontent.com/58783823/130060982-c454c73c-9bd1-415b-9206-4a10f28b2255.png">
<img width="1440" alt="Screenshot 2021-08-19 at 4 55 15 PM" src="https://user-images.githubusercontent.com/58783823/130061000-c5d2f611-de8c-43d1-867c-d65492d51f8b.png">

**Comment by sandhiyakavi** [comment]
> @sandhiyakavi are we getting response body in HEAD?

No @vikasrohit, we are not getting Response body

![image](https://user-images.githubusercontent.com/55895538/130061910-f31a09dd-d13c-4f34-9e8d-82cf73c28ec7.png)
