### ISSUE TITLE
Calling [POST]skills without challengeProminence and memberProminence parameters do not throw any errors but creates the skill 

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/skills-api#2]
**Steps**
Call https://api.topcoder-dev.com/v5.1/skills by removing challengeProminence and memberProminence parameters from the request body

Ex request:
{
	"taxonomyId":"{{taxonomyId}}",
	"name":"jump7",
	"uri":"http://www.google.com",
	"externalId":"externalId",
    "metadata": {

    }
}

An error message should be displayed if the fields memberProminence & challengeProminence are not provided in the request, but it creates the skills now

**Comment by SathyaJayabal** [comment]
@sdgun , all fields in the metadata are optional including these two. 
https://topcoder.slack.com/archives/C027Y0PLKP0/p1628238424072900
