### ISSUE TITLE
GET Skills endpoint throwing an error when using the <page> param 

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/skills-api#3]
GET Skills endpoint throwing an error when using the `page` param 
`"\"query.page\" must be a valid GUID"`

Note: 
The perPage param works fine.
The `page` param works fine for the existing skills api. 

<img width="1040" alt="Screenshot 2021-08-06 at 12 43 14 PM" src="https://user-images.githubusercontent.com/58783823/128471517-c51b6c61-bb1d-4b83-8cbb-4a3640d487db.png">

**Comment by vikasrohit** [comment]
@Sande3p I have marked it ready for review as I remember this one fixed in the last PR. Please let us know if it is not.

**Comment by sandhiyakavi** [comment]
Verified on Dev Env. Able to search with page parameter now.

![image](https://user-images.githubusercontent.com/55895538/129527682-da0d44b3-ac35-4d37-ba8b-7bfb6ea75953.png)

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-08-19 at 4 51 13 PM" src="https://user-images.githubusercontent.com/58783823/130060346-5d3ee48c-306c-43e9-9c47-e1f1d4d02c54.png">
