### ISSUE TITLE
[Get] skills doesn't return a response when search by query parameter name:Topcoder

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/skills-api#4]
**Steps**
Call https://api.topcoder-dev.com/v5.1/skills?name=Topcoder

Doesn't return any response, but name 'Wipro Digital' returns skills

https://user-images.githubusercontent.com/4592712/128473787-bb0fa8d1-f847-421b-bd94-666e407da941.mp4

**Comment by SathyaJayabal** [comment]
@sdgun , the search by name search only the skill name. The results above are for the word digital in the skill name.
