### ISSUE TITLE
PATCH skills/{skillId} endpoint does not allow to patch the metadata fields

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/skills-api#8]
PATCH skills/{skillId} endpoint does not allow to patch the metadata fields

we get the following error when trying to patch data with meta data fields
<img width="836" alt="Screenshot 2021-08-11 at 2 51 39 PM" src="https://user-images.githubusercontent.com/58783823/129004152-47dc92e8-e907-41fa-b43b-2481809facf0.png">

**Comment by vikasrohit** [comment]
Patch should be allowed for `metadata` fields of both entities.

**Comment by vikasrohit** [comment]
@Sande3p is this one fixed?

**Comment by SathyaJayabal** [comment]
Verified on dev, able to patch with metadata  fields
<img width="1032" alt="Screenshot 2021-08-18 at 5 17 37 PM" src="https://user-images.githubusercontent.com/58783823/129892856-4d76d304-4abf-4b05-8af7-34ceca7ebc02.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1680" alt="Screenshot 2021-08-19 at 6 31 46 PM" src="https://user-images.githubusercontent.com/58783823/130073968-01cbbafd-a575-48af-a4cb-9de1218e0de9.png">
